// TA-Decor sample content (Vietnamese). Loaded as a plain script -> window.TAD
window.TAD = {
  company: {
    name: 'Công Ty TNHH TM Quảng Cáo & Nội Thất TA-Decor',
    shortName: 'TA-Decor',
    tagline: 'Advertising · Interior · Design',
    hotline: '0846 316 316 - 0944 478 448',
    hotlineRaw: '0846316316',
    zaloUrl: 'https://zalo.me/0846316316',
    facebookUrl: 'https://www.facebook.com/profile.php?id=100068595892359',
    messengerUrl: 'https://m.me/100068595892359',
    email: 'tadecor@gmail.com',
    address: 'https://www.google.com/maps/place/C%C3%B4ng+Ty+TNHH+TM+Qu%E1%BA%A3ng+C%C3%A1o+V%C3%A0+N%E1%BB%99i+Th%E1%BA%A5t+Ta-Decor/@12.6952596,108.0348368,21z/data=!4m6!3m5!1s0x31721d26e84fe62b:0x433ad21ad481f5d8!8m2!3d12.6952595!4d108.0349735!16s%2Fg%2F11jpsp6yzn?entry=ttu&g_ep=EgoyMDI2MDcxMy4wIKXMDSoASAFQAw%3D%3D',
  },
  nav: [
    { label: 'Trang chủ', href: '#' },
    { label: 'Giới thiệu', href: '#gioi-thieu' },
    { label: 'Dịch vụ', href: '#dich-vu' },
    { label: 'Dự án', href: '#du-an' },
    { label: 'Tin tức', href: '#tin-tuc' },
    { label: 'Liên hệ', href: '#lien-he' },
  ],
  stats: [
    { value: 12, suffix: '+', label: 'Năm kinh nghiệm' },
    { value: 520, suffix: '+', label: 'Dự án hoàn thành' },
    { value: 380, suffix: '+', label: 'Khách hàng tin tưởng' },
  ],
  services: [
    { icon: 'pencil-ruler', title: 'Thiết kế nội thất', description: 'Concept 2D/3D theo phong cách và công năng riêng cho từng không gian sống.' },
    { icon: 'hammer', title: 'Thi công trọn gói', description: 'Đội thi công lành nghề, vật tư minh bạch, đúng thiết kế và tiến độ cam kết.' },
    { icon: 'building-2', title: 'Thiết kế văn phòng', description: 'Không gian làm việc hiệu quả, thể hiện văn hóa và hình ảnh doanh nghiệp.' },
    { icon: 'store', title: 'Showroom & cửa hàng', description: 'Bố trí trưng bày tối ưu trải nghiệm, tăng nhận diện và chuyển đổi bán hàng.' },
    { icon: 'megaphone', title: 'Bảng hiệu quảng cáo', description: 'Thiết kế, sản xuất và lắp đặt bảng hiệu, mặt dựng alu, hộp đèn, chữ nổi.' },
    { icon: 'palette', title: 'Nhận diện thương hiệu', description: 'Bộ nhận diện đồng bộ từ logo, ấn phẩm đến không gian và biển hiệu.' },
    { icon: 'printer', title: 'In ấn quảng cáo', description: 'In ấn chất lượng cao: standee, banner, backdrop, catalogue, tem nhãn.' },
    { icon: 'sparkles', title: 'Trang trí sự kiện', description: 'Dàn dựng không gian trưng bày, gian hàng và sự kiện chuyên nghiệp.' },
  ],
  filters: ['Tất cả', 'Nội thất nhà ở', 'Nội thất văn phòng', 'Showroom', 'Cửa hàng', 'Bảng hiệu quảng cáo', 'Nhận diện thương hiệu'],
  projects: [
    { title: 'Showroom Ô tô Minh Phát', category: 'Showroom', cat: 'Showroom', location: 'Quận 7, TP.HCM', year: 2024 },
    { title: 'Căn hộ Vinhomes Grand Park', category: 'Nội thất nhà ở', cat: 'Nội thất nhà ở', location: 'TP. Thủ Đức', year: 2024 },
    { title: 'Văn phòng Công ty An Phát', category: 'Nội thất văn phòng', cat: 'Nội thất văn phòng', location: 'Quận 1, TP.HCM', year: 2023 },
    { title: 'Bảng hiệu Cà phê Nhà Gỗ', category: 'Bảng hiệu quảng cáo', cat: 'Bảng hiệu quảng cáo', location: 'Gò Vấp, TP.HCM', year: 2024 },
    { title: 'Cửa hàng Thời trang LUXE', category: 'Cửa hàng', cat: 'Cửa hàng', location: 'Bình Thạnh, TP.HCM', year: 2023 },
    { title: 'Nhận diện Bakery Mộc', category: 'Nhận diện thương hiệu', cat: 'Nhận diện thương hiệu', location: 'TP.HCM', year: 2023 },
  ],
  why: [
    { icon: 'map-pinned', title: 'Khảo sát tận nơi', description: 'Đo đạc và tư vấn trực tiếp tại công trình, hoàn toàn miễn phí.' },
    { icon: 'lightbulb', title: 'Thiết kế sáng tạo', description: 'Ý tưởng độc bản, bám sát nhu cầu và công năng thực tế của bạn.' },
    { icon: 'list-checks', title: 'Quy trình rõ ràng', description: 'Từng bước minh bạch, cập nhật tiến độ thường xuyên cho khách hàng.' },
    { icon: 'receipt-text', title: 'Báo giá minh bạch', description: 'Bóc tách chi tiết hạng mục, không phát sinh ngoài hợp đồng.' },
    { icon: 'calendar-check', title: 'Đúng tiến độ', description: 'Cam kết bàn giao đúng hẹn với biên bản nghiệm thu rõ ràng.' },
    { icon: 'shield-check', title: 'Bảo hành dài hạn', description: 'Hỗ trợ và bảo hành chu đáo sau khi bàn giao công trình.' },
  ],
  process: [
    { icon: 'clipboard-list', title: 'Tiếp nhận yêu cầu', description: 'Lắng nghe nhu cầu, phong cách và ngân sách của bạn.' },
    { icon: 'ruler', title: 'Khảo sát & tư vấn', description: 'Đo đạc thực tế và tư vấn giải pháp phù hợp nhất.' },
    { icon: 'pen-tool', title: 'Thiết kế ý tưởng', description: 'Dựng concept 2D/3D để bạn hình dung không gian.' },
    { icon: 'file-signature', title: 'Báo giá & hợp đồng', description: 'Bóc tách chi phí minh bạch, ký kết rõ ràng.' },
    { icon: 'hammer', title: 'Sản xuất & thi công', description: 'Triển khai đúng thiết kế, giám sát chặt chẽ.' },
    { icon: 'clipboard-check', title: 'Nghiệm thu & bàn giao', description: 'Kiểm tra chất lượng và bàn giao đúng tiến độ.' },
    { icon: 'headphones', title: 'Bảo hành & hỗ trợ', description: 'Đồng hành và bảo hành lâu dài sau bàn giao.' },
  ],
  testimonials: [
    { rating: 5, quote: 'Đội ngũ tư vấn tận tâm, thi công đúng tiến độ và ngân sách. Căn hộ hoàn thiện vượt cả mong đợi của gia đình tôi.', name: 'Chị Ngọc Anh', role: 'Chủ căn hộ', project: 'Vinhomes Grand Park' },
    { rating: 5, quote: 'Showroom mới giúp cửa hàng tôi trông chuyên nghiệp hẳn lên. Khách vào đông hơn rõ rệt sau khi cải tạo.', name: 'Anh Hoàng Nam', role: 'Chủ showroom', project: 'Ô tô Minh Phát' },
    { rating: 5, quote: 'Từ bảng hiệu đến bộ nhận diện đều đồng bộ và đẹp. Làm việc nhanh, báo giá rõ ràng, rất đáng tin cậy.', name: 'Chị Thu Hà', role: 'Giám đốc', project: 'Bakery Mộc' },
  ],
  news: [
    { tag: 'Cẩm nang', title: '7 nguyên tắc bố trí nội thất giúp không gian rộng thoáng hơn', date: '12/06/2024', read: '5 phút đọc' },
    { tag: 'Kinh nghiệm', title: 'Chọn bảng hiệu quảng cáo: chất liệu nào bền và đẹp nhất?', date: '28/05/2024', read: '6 phút đọc' },
    { tag: 'Báo giá', title: 'Chi phí thi công nội thất trọn gói 2024 gồm những gì?', date: '15/05/2024', read: '8 phút đọc' },
  ],
  budgets: ['Dưới 10 triệu', '10 – 20 triệu', '20 – 30 triệu', '30 triệu – 40 triệu', 'Trên 40 triệu'],
};
